Featurelogin
MALLTECH/KigaliPhoneCenterMIS pull request #4
Opened 2020-09-27 22:52 UTC by wemajosias

2020-09-27 23:01 UTC, rukundoeric reviewed
Remove spaces in login.php

2020-09-30 21:45 UTC, rukundoeric requested changes
# Status: REQUIRED CHANGES :warning: :construction: 
* Man ndabona byose ari sawa kbs, gusa haraburamo twa text hasi ya inputs fields mugihe password ibaye incorrect cyanga username ari invalid

2020-10-01 21:28 UTC, IradukundaYves approved these changes

2020-10-02 22:53 UTC, rukundoeric approved these changes

2020-10-02 22:59 UTC, merged